
ALTER TABLE CLIENTE RENAME COLUMN SEXO TO GENERO;
DESC CLIENTE;

ALTER TABLE EMPLEADO MODIFY ID_EMPLEADO NUMBER(30);
DESC EMPLEADO;

--PK
ALTER TABLE RESERVACION ADD CONSTRAINTS PK_ID_RESERVACION PRIMARY KEY (ID_RESERVACION); 
ALTER TABLE PRODUCTO ADD CONSTRAINTS PK_ID_PRODUCTO PRIMARY KEY (ID_PRODUCTO); 

ALTER TABLE TIPO_SALA ADD CONSTRAINTS PK_ID_TIPO PRIMARY KEY (ID_TIPO); 
ALTER TABLE OPINION_ESPECTADOR ADD CONSTRAINTS PK_ID_OPINION PRIMARY KEY (ID_OPINION); 

ALTER TABLE PROMOCION ADD CONSTRAINTS PK_ID_PROMOCION PRIMARY KEY (ID_PROMOCION); 
ALTER TABLE TICKET ADD CONSTRAINTS PK_ID_TICKET PRIMARY KEY (ID_TICKET); 

ALTER TABLE CLIENTE ADD CONSTRAINTS PK_ID_CLIENTE PRIMARY KEY (ID_CLIENTE); 
ALTER TABLE EMPLEADO ADD CONSTRAINTS PK_ID_EMPLEADO PRIMARY KEY (ID_EMPLEADO); 

ALTER TABLE SALA ADD CONSTRAINTS PK_ID_SALA PRIMARY KEY (ID_SALA); 
ALTER TABLE ROL ADD CONSTRAINTS PK_ID_ROL PRIMARY KEY (ID_ROL); 

ALTER TABLE SERVICIO ADD CONSTRAINTS PK_ID_SERVICIO PRIMARY KEY (ID_SERVICIO); 
ALTER TABLE CARTELERA ADD CONSTRAINTS PK_ID_CARTELERA PRIMARY KEY (ID_CARTELERA); 

ALTER TABLE REPARTO ADD CONSTRAINTS PK_ID_REPARTO PRIMARY KEY (ID_REPARTO); 
ALTER TABLE PELICULA ADD CONSTRAINTS PK_ID_PELICULA PRIMARY KEY (ID_PELICULA);

ALTER TABLE CINE ADD CONSTRAINTS PK_ID_CINE PRIMARY KEY (ID_CINE); 
ALTER TABLE FUNCION ADD CONSTRAINTS PK_ID_FUNCION PRIMARY KEY (ID_FUNCION);

--FK
ALTER TABLE CLIENTE ADD CONSTRAINTS FK_CLIENTE_RESERVACION FOREIGN KEY (ID_RESERVACION) REFERENCES RESERVACION (ID_RESERVACION); 
ALTER TABLE EMPLEADO ADD CONSTRAINTS FK_EMPLEADO_GERENTE FOREIGN KEY (ID_GERENTE) REFERENCES EMPLEADO (ID_EMPLEADO); 

ALTER TABLE SALA ADD CONSTRAINTS FK_SALA_TIPO_SALA FOREIGN KEY (ID_TIPO) REFERENCES TIPO_SALA (ID_TIPO); 
ALTER TABLE ROL ADD CONSTRAINTS FK_ROL_DIRECTOR FOREIGN KEY (ID_DIRECTOR) REFERENCES ROL (ID_ROL); 

ALTER TABLE SERVICIO ADD CONSTRAINTS FK_SERVICIO_PROMOCION FOREIGN KEY (ID_PROMOCION) REFERENCES PROMOCION (ID_PROMOCION); 
ALTER TABLE CARTELERA ADD CONSTRAINTS FK_CARTELERA_PELICULA FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA (ID_PELICULA); 
ALTER TABLE REPARTO ADD CONSTRAINTS FK_REPARTO_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL); 

ALTER TABLE PELICULA ADD CONSTRAINTS FK_PELICULA_OPINION FOREIGN KEY (ID_OPINION) REFERENCES OPINION_ESPECTADOR (ID_OPINION); 
ALTER TABLE PELICULA ADD CONSTRAINTS FK_PELICULA_REPARTO FOREIGN KEY (ID_REPARTO) REFERENCES REPARTO (ID_REPARTO); 

ALTER TABLE CINE ADD CONSTRAINTS FK_CINE_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO); 

ALTER TABLE CINE ADD CONSTRAINTS FK_CINE_SALA FOREIGN KEY (ID_SALA) REFERENCES SALA (ID_SALA); 
ALTER TABLE CINE ADD CONSTRAINTS FK_CINE_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO); 

ALTER TABLE CINE ADD CONSTRAINTS FK_CINE_CARTELERA FOREIGN KEY (ID_CARTELERA) REFERENCES CARTELERA (ID_CARTELERA); 
ALTER TABLE CINE ADD CONSTRAINTS FK_CINE_SERVICIO FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIO (ID_SERVICIO); 

ALTER TABLE FUNCION ADD CONSTRAINTS FK_FUNCION_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE); 
ALTER TABLE FUNCION ADD CONSTRAINTS FK_FUNCION_TICKET FOREIGN KEY (ID_TICKET) REFERENCES TICKET (ID_TICKET); 
ALTER TABLE FUNCION ADD CONSTRAINTS FK_FUNCION_CINE FOREIGN KEY (ID_CINE) REFERENCES CINE (ID_CINE); 