DROP SEQUENCE SQ_ID_RESERVACION;
DROP SEQUENCE SQ_ID_PRODUCTO;
DROP SEQUENCE SQ_ID_TIPO_SALA;
DROP SEQUENCE SQ_ID_OPINION_ESPECTADOR;
DROP SEQUENCE SQ_ID_PROMOCION;
DROP SEQUENCE SQ_ID_TICKET;
DROP SEQUENCE SQ_ID_CLIENTE;
DROP SEQUENCE SQ_ID_EMPLEADO;
DROP SEQUENCE SQ_ID_SALA;
DROP SEQUENCE SQ_ID_ROL;
DROP SEQUENCE SQ_ID_SERVICIO;
DROP SEQUENCE SQ_ID_REPARTO;
DROP SEQUENCE SQ_ID_FUNCION;
DROP SEQUENCE SQ_ID_PELICULA;
DROP SEQUENCE SQ_ID_CARTELERA;
DROP SEQUENCE SQ_ID_CINE;

--1
CREATE SEQUENCE SQ_ID_RESERVACION
START WITH 1
INCREMENT BY 1;

--2
CREATE SEQUENCE SQ_ID_PRODUCTO
START WITH 1
INCREMENT BY 1;

--3
CREATE SEQUENCE SQ_ID_TIPO_SALA
START WITH 1
INCREMENT BY 1;

-- 4
CREATE SEQUENCE SQ_ID_OPINION_ESPECTADOR
START WITH 1
INCREMENT BY 1;

-- 5
CREATE SEQUENCE SQ_ID_PROMOCION
START WITH 1
INCREMENT BY 1;

-- 6
CREATE SEQUENCE SQ_ID_TICKET
START WITH 1
INCREMENT BY 1;

-- 7
CREATE SEQUENCE SQ_ID_CLIENTE
START WITH 1
INCREMENT BY 1;

-- 8
CREATE SEQUENCE SQ_ID_EMPLEADO
START WITH 1
INCREMENT BY 1;

-- 9
CREATE SEQUENCE SQ_ID_SALA
START WITH 1
INCREMENT BY 1;

-- 10
CREATE SEQUENCE SQ_ID_ROL
START WITH 1
INCREMENT BY 1;

-- 11
CREATE SEQUENCE SQ_ID_SERVICIO
START WITH 1
INCREMENT BY 1;

-- 12
CREATE SEQUENCE SQ_ID_REPARTO
START WITH 1
INCREMENT BY 1;

-- 13
CREATE SEQUENCE SQ_ID_PELICULA
START WITH 1
INCREMENT BY 1;

-- 14
CREATE SEQUENCE SQ_ID_CARTELERA
START WITH 1
INCREMENT BY 1;

-- 15
CREATE SEQUENCE SQ_ID_CINE
START WITH 1
INCREMENT BY 1;

-- 16
CREATE SEQUENCE SQ_ID_FUNCION
START WITH 1
INCREMENT BY 1;